#Noor A Alam (ID: 2215151014)
#Tasks:<br>
    Use numpy to create a 3×3 matrix of random integers between 1 and 50.  
    1) Run the code twice
    2) With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.  
    3) Without setting a seed, allowing random values to change each time.  
    4) Observe and explain the differences in outputs.  (in a different cell as text)

In [12]:
import numpy as np
x = np.random.randint(1,51,size=(3,3))
print(x)

[[49 42 49]
 [20 24 18]
 [48  4 20]]


In [16]:
np.random.seed(10)
x = np.random.randint(1,51,size=(3,3))
print(x)

[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [18]:
x = np.random.randint(1,51,size=(3,3))
print(x)

[[37 48 12]
 [25 44 34]
 [ 9 37 15]]


#Observation and explaination

While using a fixed seed (np.random.seed(10)), NumPy ensures that the same random numbers are generated every time the code runs. This makes results reproducible, which is useful for debugging and sharing code.

Without setting a seed, NumPy generates truly random numbers each time.Thus, the matrix values will change with every execution, making the outputs unpredictable.